spring.application.name=prodotti

spring.datasource.url=jdbc:mysql://localhost:3307/prodotti
spring.datasource.username=servizio_java
spring.datasource.password=ServizioJava123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
